### ISSUE TITLE
[Feature Request] Add support for Log forwarding to lang-side

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-dotnet#140]
### Describe the solution you'd like

Add support for Log forwarding to lang-side. This would be functionally similar to what already exists in TypeScript SDK, though we may want to consider a solution for .NET where logs are passed directly from core to lang side, without buffering (akin to what has been done for metrics forwarding).

A corresponding option already exists (as [seen here](https://github.com/temporalio/sdk-dotnet/blob/ab4ded44cb15c2aba6ef7472e712ba12f3fef6ad/src/Temporalio/Bridge/src/runtime.rs#L212-L215)) and triggers registration of the Log forwarding export layer in Bridge, but log entries never get polled by lang, so this practically behave as a noop log exporter.

**Comment by cretz** [comment]
I have opened https://github.com/temporalio/sdk-core/issues/618 which this will depend on because we'd surely want this push based in .NET where there is not as much FFI overhead as there is in other languages. (basically match the behavior of metrics)
