### ISSUE TITLE
[Feature Request] Add support for Temporal Schedule

### ISSUE THREAD

**Issue by dodyg** [temporalio/sdk-dotnet#160]
https://temporal.io/blog/temporal-schedules-reliable-scalable-and-more-flexible-than-cron-jobs

**Comment by Quinn-With-Two-Ns** [comment]
The DotNet SDK has full schedules support https://dotnet.temporal.io/api/Temporalio.Client.Schedules.html

There is also a [sample ](https://github.com/temporalio/samples-dotnet/tree/main/src/Schedules)available

**Comment by dodyg** [comment]
Ah ok. It wasn't mentioned in the blog post

![image](https://github.com/temporalio/sdk-dotnet/assets/1761249/97dd95cb-2bf5-4f8c-96be-38fa8d4d5a8f)

**Comment by Quinn-With-Two-Ns** [comment]
The blog post should be updated now,  thanks for pointing this out.
