### ISSUE TITLE
[Bug] README workflow testing samples are not running the worker

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-dotnet#162]
### Describe the bug

README samples in the workflow testing area are not actually running the worker

**Comment by eugbyte** [comment]
Same, I faced a timeout issue. The test environmentt Client just keeps running without actually executing the Workflow provided, eventually timing out the test.

I copied and pasted the example under [Workflow testing](https://github.com/temporalio/sdk-dotnet?tab=readme-ov-file#workflow-testing). 

I am using XUnit, Windows OS (x64).

`MockWaitADayWorkflow.cs`
```
[Workflow]
public class MockWaitADayWorkflow {
    [WorkflowRun]
    public async Task<string> RunAsync() {
        await Workflow.DelayAsync(TimeSpan.FromSeconds(1));
        return "all done";
    }
}
```

`TestTemporalWorkflow .cs`
```
using NanoidDotNet;

public class TestTemporalWorkflow {
    [Fact(Timeout = 5_000)]
    public async Task SimpleMockedWorkflow() {
        await using var env = await WorkflowEnvironment.StartTimeSkippingAsync();
        using var worker = new TemporalWorker(
          env.Client,
          new TemporalWorkerOptions($"task-queue-{Nanoid.Generate()}").
              AddWorkflow<MockWaitADayWorkflow>());
        var result = await env.Client.ExecuteWorkflowAsync(
            (MockWaitADayWorkflow wf) => wf.RunAsync(),
            new(id: $"wf-{Nanoid.Generate()}", taskQueue: worker.Options.TaskQueue!));
        Assert.Equal("all done", result);
    }
}
```

I get the error that the test has timed out: `Test execution timed out after 5000 milliseconds`.

**Comment by eugbyte** [comment]
Also, I added breakpoints within the `RunAsync` method of the `MockWaitADayWorkflow` class and the break point is never reached.

**Comment by eugbyte** [comment]
Similar to https://github.com/temporalio/sdk-dotnet/issues/179#issue-2092746994

**Comment by cretz** [comment]
Yes, we need to fix that README. In the sample code you are not actually running/executing the worker which you must do. I will update shortly. This is unrelated to the other issue (time skipping test server and workflow update).
