### ISSUE TITLE
[Bug] Failed decoding parameters

### ISSUE THREAD

**Issue by dev-danx** [temporalio/sdk-dotnet#165]
Sending jsonString as parameter to activity

{"message":"Failed decoding parameters","source":"","stackTrace":"   at Temporalio.Worker.ActivityWorker.ExecuteActivityInternalAsync(RunningActivity act, ActivityTask tsk)","encodedAttributes":null,"cause":{"message":"The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1.","source":"","stackTrace":"   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)\n   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)\n   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)\n   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)\n   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)\n   at Temporalio.Converters.JsonPlainConverter.ToValue(Payload payload, Type type)\n   at Temporalio.Converters.DefaultPayloadConverter.ToValue(Payload payload, Type type)\n   at Temporalio.Converters.ConverterExtensions.ToSingleValueAsync(DataConverter converter, IReadOnlyCollection`1 payloads, Type type)\n   at Temporalio.Worker.ActivityWorker.ExecuteActivityInternalAsync(RunningActivity act, ActivityTask tsk)","encodedAttributes":null,"cause":{"message":"Cannot get the value of a token type 'StartObject' as a string.","source":"","stackTrace":"   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)\n   at System.Text.Json.Utf8JsonReader.GetString()\n   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)\n   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)","encodedAttributes":null,"cause":null,"applicationFailureInfo":{"type":"InvalidOperationException","nonRetryable":false,"details":null}},"applicationFailureInfo":{"type":"JsonException","nonRetryable":false,"details":null}},"applicationFailureInfo":{"type":"","nonRetryable":false,"details":null}}

**Comment by cretz** [comment]
If you're sending a string as a parameter, the parameter type needs to be string. If you're sending an object, you send the object and the data converter converts it to JSON for you. Can you show exact code of the issue?

(also feel free to join us on the #dotnet-sdk channel on [Slack](https://t.mp/slack))

**Comment by dev-danx** [comment]
you are correct
