### ISSUE TITLE
[Bug] Child Workflow Cancellation before scheduled surfaces as incorrect error

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-dotnet#178]
### Describe the bug

If a child workflow is cancelled before it's scheduled, this (can) surface as a `ChildWorkflowFailureException` when it should instead be a `CanceledFailureException` as with other cancellations.

There is some code [here](https://github.com/temporalio/sdk-dotnet/blob/71757a66e152e49ddff2955dc464f8111cd10b07/src/Temporalio/Worker/WorkflowInstance.cs#L1782) that attempts to do the right thing, but this code may not always get to run before things have been handed off to Core (as is the case here). Probably we don't even need to have that code, Core will do the right thing and the failure it returns for the child just needs to be interpreted properly.

### Minimal Reproduction

Reproduced during fuzz testing, but just cancelling children immediately or near-immedately ought to do it.

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by cretz** [comment]
After discussion, throwing cancellation exceptions eagerly if a call is made with an already-cancelled token is the .NET way and we do it in timers as well. So we need to just document that calling with an already-cancelled token may have a different exception than if it's cancelled before started (or after started). And that users should use `TemporalException.IsCanceledException` helper to know whether an exception is a cancelled exception.
