### ISSUE TITLE
[Feature Request] Dependency Injection into a workflow

### ISSUE THREAD

**Issue by rsr-maersk** [temporalio/sdk-dotnet#181]
Thanks for the good sdk

### Describe the solution you'd like

Allow "Workflow" static obejct to have a Scoped ServiceCollection scoped, or allow ctor DI

**Comment by cretz** [comment]
Workflows must be deterministic and therefore must access nothing external directly and therefore we do not want dependency injection for workflows. From https://github.com/temporalio/sdk-dotnet/tree/main/src/Temporalio.Extensions.Hosting:

> Workflows are inherently self-contained, deterministic units of work and therefore should never call anything external. Therefore, there is no such thing as dependency injection for workflows, their construction and lifetime is managed by Temporal.

Also, feel free to join us on #dotnet-sdk channel on https://t.mp/slack or on the forums at https://community.temporal.io/.

(closing as not an issue, but feel free to continue adding comments or joining us in one of the places above)

**Comment by rsr-maersk** [comment]
@cretz  "deterministic". Why?
This goes against SOLID. And doesn't make sense to me.

**Comment by cretz** [comment]
> "deterministic". Why?

See https://docs.temporal.io/workflows#deterministic-constraints. Workflow environments and constraints are not like other code. This same constraint exists in Azure Durable Functions and others that implement the event sourcing model to support durable function resumption.
