### ISSUE TITLE
[Bug] [Blazor Webassembly] System.Diagnostics.Process is not supported on this platform

### ISSUE THREAD

**Issue by djnice** [temporalio/sdk-dotnet#184]
When I try to start a workflow, an exception occurs as mentioned in the subject.

The error is in line 41 of TemporalConnection.cs:
options.Identity ??= System.Diagnostics.Process.GetCurrentProcess().Id

Please use the System.Environment.ProcessId method instead, it works under Webassembly and also more efficient:
[https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1837](url)

**Comment by cretz** [comment]
> Please use the System.Environment.ProcessId method instead

That is not supported across all .NET versions this library supports. We could use compiler directives to use this newer approach with newer .NET versions, but you're going to hit other WASM issues with this SDK.

> it works under Webassembly and also more efficient:

We use a Rust-based core for this library via P/Invoke and therefore it won't be Blazor/WASM compatible anyways. Our Rust-based core is not WASM capable at this time.

**Comment by cretz** [comment]
(closing as question, but feel free to respond or join us on Slack or our forums)
