### ISSUE TITLE
[Bug] AddAllActivities not working

### ISSUE THREAD

**Issue by eugbyte** [temporalio/sdk-dotnet#187]
### What are you really trying to do?

Unit testing workflow with mock activity.
### Describe the bug
I created a MockActivity
```
public class MockActivities : IActivities {
    [Activity]
    public string GetName(string id) => "abc";
    [Activity]
    public string GetSurname(string id) => "def";
}

```

When I tried to mock the activity for the unit test, e.g.
```
[Fact]
public async Task WorkflowSucceeds() {
await using var env = await WorkflowEnvironment.StartTimeSkippingAsync();
using var worker = new TemporalWorker(
  env.Client,
  new TemporalWorkerOptions($"task-queue-{Guid.NewGuid()}")
  .AddAllActivities<IActivities>(new MockActivities())
  .AddWorkflow<MyWorkflow>());
}

```

I get the following error:
```
System.ArgumentException : No activities found on MyNamespace (Parameter 'type')
```

**Comment by eugbyte** [comment]
Ok I found the reason.

The `[Activity]` attribute must not only be added to the method, but also the interface should the Activity Class implement the interface, e.g.

```
public interface IActivity {
    [Activity]
    public async Task<string> GetName(string id);
}

public class MockActivities : IActivities {
    [Activity]
    public async Task<string> GetName(string id) => "abc";
}

```

Will be good if you can amend the documentation to specify that the `[Activity]` also be added to interfaces which Activity class implement.

**Comment by cretz** [comment]
Yes, I will make a note to make it clear that the attribute is intentionally not inherited and needs to be in both place if the definition and implementation are in separate places.
