### ISSUE TITLE
[Bug] Cannot add multiple versions of a workflow using DI

### ISSUE THREAD

**Issue by marcusbooyah** [temporalio/sdk-dotnet#212]
### What are you really trying to do?

Trying to add two versions of the same workflow using dependency injection.

### Describe the bug

It's possible to add multiple workflows using this method, the part that makes it break is having two workflows with the same name in the `WorkflowAttribute`, even though they are being registered with different build IDs.

 I talked with @cretz who said:
> Yes, this is a bug. This is because the DI setup predates versioning, so we only supported one worker per task queue in a service collection: [https://github.com/temporalio/sdk-dotnet/blob/c6b7aca05cdd2b61e4b99098f3f390469232[…]3a4a/src/Temporalio.Extensions.Hosting/TemporalWorkerService.cs](https://github.com/temporalio/sdk-dotnet/blob/c6b7aca05cdd2b61e4b99098f3f3904692323a4a/src/Temporalio.Extensions.Hosting/TemporalWorkerService.cs#L90). We need to change what we uniquely identify options set as on the container to include build ID

### Minimal Reproduction
```csharp
[Workflow("my-workflow")]
public class TestWorkflow
{
    [WorkflowRun]
    public Task RunAsync() => Workflow.DelayAsync(TimeSpan.FromSeconds(3));
}

[Workflow("my-workflow")]
public class TestWorkflowV2
{
    [WorkflowRun]
    public Task RunAsync() => Workflow.DelayAsync(TimeSpan.FromSeconds(1));
}

static async Task Main(string[] args)
{
    await using var env = await WorkflowEnvironment.StartTimeSkippingAsync();

    IHost host = Host.CreateDefaultBuilder()
        .ConfigureServices(services =>
        {
            services.AddSingleton(env.Client);
            services
                .AddHostedTemporalWorker("task-queue")
                    .ConfigureOptions(options =>
                    {
                        options.UseWorkerVersioning  = true;
                        options.BuildId                            = "1.0";
                    })
                    .AddWorkflow<TestWorkflow>();

            services
                .AddHostedTemporalWorker("task-queue")
                    .ConfigureOptions(options =>
                    {
                        options.UseWorkerVersioning  = true;
                        options.BuildId                           = "2.0";
                    })
                    .AddWorkflow<TestWorkflowV2>();
        })
        .Build();

    host.Run();
}
```
### Environment/Versions

- OS and processor: [Windows]
- Temporal Version: SDK 1.0.0

**Comment by cretz** [comment]
💥 Note, in #451 we have changed some behavior here where we now no longer assume this non-GA-will-be-removed form versioning when build ID is present.
