### ISSUE TITLE
Temporal CLI based ephemeral server

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-dotnet#22]
- [ ] Opt out of version check for servers started by the SDK test framework - there's no value for users since we typically start it without the UI and can't show upgrade notifications

**Comment by bergundy** [comment]
Depends on https://github.com/temporalio/sdk-core/issues/485

No need to maintain support for Temporalite.

**Comment by cretz** [comment]
Closing as duplicate of #50
