### ISSUE TITLE
[Bug] WaitConditionAsync is run outside of Workflow context

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-dotnet#240]
### Describe the bug

The callback for `WaitConditionAsync` is run outside of the event loop, so the current task scheduler is not the workflow instance. This means any calls on the `Workflow` object within the callback will fail.

**Comment by Tyler-Harker** [comment]
Workflow event loop is in the following file (for future reference)

https://github.com/temporalio/sdk-dotnet/blob/ee378c17595bccf8a390ff82e4e1f514d4a6344f/src/Temporalio/Worker/WorkflowInstance.cs#L648
