### ISSUE TITLE
NU1903 error when run dotnet build 

### ISSUE THREAD

**Issue by rstm-sf** [temporalio/sdk-dotnet#347]
**Summary**

When I try to build a solution, I get errors NU1903

**Details**

```bash
> dotnet build
    .\sdk-dotnet\tests\Temporalio.Tests\Temporalio.Tests.csproj : error NU1903: Warning As Error: Package 'System.Net.Http' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-7jgj-8wvc-jh57
    .\sdk-dotnet\src\Temporalio.Extensions.Hosting\Temporalio.Extensions.Hosting.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 7.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
    .\sdk-dotnet\tests\Temporalio.Tests\Temporalio.Tests.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
    .\sdk-dotnet\tests\Temporalio.Tests\Temporalio.Tests.csproj : error NU1903: Warning As Error: Package 'System.Text.RegularExpressions' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-cmhx-cq75-c4mj
```

Restore failed with 4 error(s) in 0.7s

**Comment by cretz** [comment]
Hrmm, these issues do not occur in our CI build when we do a `dotnet build`. I wonder if our `dotnet` version is off. For instance, https://github.com/temporalio/sdk-dotnet/actions/runs/10812517816 is not reporting this. Can you provide the steps to replicate this build error? Is there a global setting you have that we do not in CI?

Regardless, we can definitely update the test dependencies. For the `Temporalio.Extensions.Hosting` dependency I'm a bit more hesitant to require the next major version (though of course we suggest all _users_ of the library use the latest), but we may be able to upgrade that too.

**Comment by rstm-sf** [comment]
Seems to be because [the .NET 6 SDK is being used](
https://github.com/temporalio/sdk-dotnet/blob/5141c2cb1330cdce1ab88f1bffd246012d5e1aa7/.github/workflows/ci.yml#L47) and it may not have up-to-date package checking for known vulnerabilities.


I have SDKs from 6 to 9 and when I build, I used global.json to specify that I should use SDK 8. Now I tried to specify 6 SDK and there were no errors either
```bash
dotnet build
MSBuild version 17.3.4+a400405ba for .NET
  Determining projects to restore...
  Restored .\sdk-dotnet\src\Temporalio.Extensions.OpenTelemetry\Temporalio.Extensions.OpenTelemetry.csproj (in 193 ms).
  Restored .\sdk-dotnet\src\Temporalio.Extensions.DiagnosticSource\Temporalio.Extensions.DiagnosticSource.csproj (in 193 ms).
  Restored .\sdk-dotnet\src\Temporalio.Extensions.Hosting\Temporalio.Extensions.Hosting.csproj (in 213 ms).
  Restored .\sdk-dotnet\src\Temporalio\Temporalio.csproj (in 193 ms).
  Restored .\sdk-dotnet\tests\Temporalio.Tests\Temporalio.Tests.csproj (in 232 ms).
  Temporalio -> .\sdk-dotnet\src\Temporalio\bin\Debug\netcoreapp3.1\Temporalio.dll
  Temporalio -> .\sdk-dotnet\src\Temporalio\bin\Debug\netstandard2.0\Temporalio.dll
  Temporalio -> .\sdk-dotnet\src\Temporalio\bin\Debug\net462\Temporalio.dll
  Temporalio.Extensions.DiagnosticSource -> .\sdk-dotnet\src\Temporalio.Extensions.DiagnosticSource\bin\Debug\netstandard2.0\Temporalio.Extensions.DiagnosticSource.dll
  Temporalio.Extensions.OpenTelemetry -> .\sdk-dotnet\src\Temporalio.Extensions.OpenTelemetry\bin\Debug\netstandard2.0\Temporalio.Extensions.OpenTelemetry.dll
  Temporalio.Extensions.Hosting -> .\sdk-dotnet\src\Temporalio.Extensions.Hosting\bin\Debug\netstandard2.0\Temporalio.Extensions.Hosting.dll
  Temporalio.Extensions.Hosting -> .\sdk-dotnet\src\Temporalio.Extensions.Hosting\bin\Debug\net462\Temporalio.Extensions.Hosting.dll
  Temporalio.Extensions.DiagnosticSource -> .\sdk-dotnet\src\Temporalio.Extensions.DiagnosticSource\bin\Debug\net462\Temporalio.Extensions.DiagnosticSource.dll
  Temporalio.Extensions.OpenTelemetry -> .\sdk-dotnet\src\Temporalio.Extensions.OpenTelemetry\bin\Debug\net462\Temporalio.Extensions.OpenTelemetry.dll
  Temporalio.Extensions.Hosting -> .\sdk-dotnet\src\Temporalio.Extensions.Hosting\bin\Debug\net6.0\Temporalio.Extensions.Hosting.dll
  Temporalio.Tests -> .\sdk-dotnet\tests\Temporalio.Tests\bin\Debug\net6.0\Temporalio.Tests.dll
```

```json
{
  "sdk": {
    "version": "6.0.0",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}
```

**Comment by cretz** [comment]
Thanks! We will look into setting up a build with .NET 8 and look into updating minimum dependencies in a way that doesn't harm past users.

This should just affect builds of the SDK not usage of the SDK so we likely won't release an emergency patch release for this, but we should get to this soon. You can either alter the dependency versions explicitly or disable this warning in the meantime.

**Comment by cretz** [comment]
@rstm-sf - I used .NET 8 in a part of our CI at https://github.com/temporalio/sdk-dotnet/pull/356 and did not see any errors restoring/building (see run at https://github.com/temporalio/sdk-dotnet/actions/runs/11239495901/job/31246675940?pr=356, it is windows specific).

It does seem like per https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-restore-audit that this should fail if it had bad dependencies. I wonder if a fresh build is pulling in fixed versions of those dependencies? Or is there some other setting governing this? We have `TreatWarningsAsErrors` as `true`. I wonder if related to `net6.0` target framework. I want to make sure we replicate the failure in CI so I know I have fixed it and I know we won't see it again.

**Comment by rstm-sf** [comment]
@cretz hello, sorry for delay, I reproduced it :) https://github.com/rstm-sf/sdk-dotnet/actions/runs/11425577349/job/31787420591?pr=1

```bash
Run dotnet build
  Determining projects to restore...
/home/runner/work/sdk-dotnet/sdk-dotnet/src/Temporalio/Temporalio.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.4 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4 [/home/runner/work/sdk-dotnet/sdk-dotnet/Temporalio.sln]
  Restored /home/runner/work/sdk-dotnet/sdk-dotnet/src/Temporalio.Extensions.OpenTelemetry/Temporalio.Extensions.OpenTelemetry.csproj (in 3.07 sec).
  Restored /home/runner/work/sdk-dotnet/sdk-dotnet/src/Temporalio.Extensions.Hosting/Temporalio.Extensions.Hosting.csproj (in 3.09 sec).
  Failed to restore /home/runner/work/sdk-dotnet/sdk-dotnet/src/Temporalio/Temporalio.csproj (in 3.07 sec).
  Restored /home/runner/work/sdk-dotnet/sdk-dotnet/src/Temporalio.Extensions.DiagnosticSource/Temporalio.Extensions.DiagnosticSource.csproj (in 4 ms).
  Restored /home/runner/work/sdk-dotnet/sdk-dotnet/tests/Temporalio.Tests/Temporalio.Tests.csproj (in 6.95 sec).

Build FAILED.

/home/runner/work/sdk-dotnet/sdk-dotnet/src/Temporalio/Temporalio.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.4 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4 [/home/runner/work/sdk-dotnet/sdk-dotnet/Temporalio.sln]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:10.98
Error: Process completed with exit code 1.
```

**Comment by rstm-sf** [comment]
Maybe using
```xml
<WarningsNotAsErrors>NU1903</WarningsNotAsErrors>
```
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#warningsaserrors-and-warningsnotaserrors

**Comment by cretz** [comment]
Thanks! I wonder what was different about our PRs. I wonder if my use of `8` instead of `8.x` is the issue? Regardless, yes we should at least update `System.Text.Json` dependency because we're already on `8`, but I do want to make sure our CI is catching these going forward (we are also getting a security alert on this dependency internally with dependabot). I will try again to make the CI fail (I do want to keep a 6.x build around in CI too).

**Comment by cretz** [comment]
That was it, it's that I used `8` instead of `8.x`. Fixing this now...
