### ISSUE TITLE
[Feature Request] what is the roadmap for this sdk,  really need it 

### ISSUE THREAD

**Issue by charzhao** [temporalio/sdk-dotnet#38]

**Comment by cretz** [comment]
@charzhao - The workflow portion of the SDK is under active development and should be released within the next couple of weeks. Once done, it will be full featured like any other SDK (but still alpha), only advanced pieces like source generator and static analyzer will remain. There are no exact roadmap dates. We put proposals at https://github.com/temporalio/proposals/tree/master/dotnet.

Closing as question (feel free to ask future questions on our forum or community Slack or just as another comment here)
