### ISSUE TITLE
When you planning to Release your product

### ISSUE THREAD

**Issue by P9avel** [temporalio/sdk-dotnet#49]
Hi, we are planning to start new projecct. And i want to use Temporal. All team members is C# developers. Please say, when  you planning to Release your product. We want to use your sdk in production. please say ETA

**Comment by cretz** [comment]
We are making the next alpha release soon (after #48 merged) and need feedback to help us get to GA. The more feedback we get the more we can feel confident in a GA release. Please join us on `#dotnet-sdk` on [Slack](http://t.mp/slack) or on [the forums](https://community.temporal.io) for general questions.

(closing as not an actionable issue)
